[site]
title = "Hao Huang"
description = "JSD student at Cornell University Law School"
favicon = "/favicon.svg"
last_updated = "July 20, 2026"

[author]
name = "Hao Huang"
title = "JSD Student"
institution = "Cornell University Law School"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "hh874@cornell.edu"
location = "Ithaca, NY"
location_url = "https://www.google.com/maps/place/Cornell+Law+School/@42.443864,-76.4884071,901m/data=!3m3!1e3!4b1!5s0x89d0818ea34dbe71:0x190ef4b9c68465a!4m6!3m5!1s0x89d0818ea283619b:0x443477d31cf3a273!8m2!3d42.443864!4d-76.4858268!16zL20vMDF3cndm?entry=ttu&g_ep=EgoyMDI2MDcxNS4wIKXMDSoASAFQAw%3D%3D"
location_details = [
  "Myron Taylor Hall, Ithaca, NY 14853"
  ]
google_scholar = "https://scholar.google.com/citations?user=G3o0QYMAAAAJ&hl=en"
ssrn = "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=4928387"
linkedin = "https://www.linkedin.com/in/hao-huang-law/?skipRedirect=true"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
